### ISSUE TITLE
BeagleBoard-exercises/displays/ili9341/fb/off.sh script results in ./backlight.py: No such file or directory

### ISSUE THREAD

**Issue by jomoengineer** [MarkAYoder/BeagleBoard-exercises#4]
The script BeagleBoard-exercises/displays/ili9341/fb/off.sh calls backlight.py which does not exist in the fb folder, however a LCD-backlight.py does.  Changing the call to LCD-backlight.py corrects the issue. 

I set the line to:
'
  \# Turn off LED
    ./LCD-backlight.py 0
'

**Comment by MarkAYoder** [comment]
Good catch.  It's been fixed.

--Mark
